[2022-06-07 13:55:05,605] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: todoist_load_to_pg.generate_sql manual__2022-06-07T13:55:01.940790+00:00 [queued]>
[2022-06-07 13:55:05,619] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: todoist_load_to_pg.generate_sql manual__2022-06-07T13:55:01.940790+00:00 [queued]>
[2022-06-07 13:55:05,620] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 13:55:05,620] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-06-07 13:55:05,621] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 13:55:05,635] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): generate_sql> on 2022-06-07 13:55:01.940790+00:00
[2022-06-07 13:55:05,640] {standard_task_runner.py:52} INFO - Started process 226 to run task
[2022-06-07 13:55:05,652] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'todoist_load_to_pg', 'generate_sql', 'manual__2022-06-07T13:55:01.940790+00:00', '--job-id', '463', '--raw', '--subdir', 'DAGS_FOLDER/todoist_load_to_pg.py', '--cfg-path', '/tmp/tmp9orpsqo9', '--error-file', '/tmp/tmpn0veavh_']
[2022-06-07 13:55:05,654] {standard_task_runner.py:77} INFO - Job 463: Subtask generate_sql
[2022-06-07 13:55:05,728] {logging_mixin.py:109} INFO - Running <TaskInstance: todoist_load_to_pg.generate_sql manual__2022-06-07T13:55:01.940790+00:00 [running]> on host bd658c040114
[2022-06-07 13:55:05,802] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=emil
AIRFLOW_CTX_DAG_ID=todoist_load_to_pg
AIRFLOW_CTX_TASK_ID=generate_sql
AIRFLOW_CTX_EXECUTION_DATE=2022-06-07T13:55:01.940790+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-07T13:55:01.940790+00:00
[2022-06-07 13:55:05,804] {todoist_load_to_pg.py:39} INFO - ['id', 'order', 'color', 'name', 'comment_count', 'shared', 'favorite', 'sync_id', 'url'], ключи
[2022-06-07 13:55:05,805] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/bitnami/airflow/dags/todoist_load_to_pg.py", line 47, in generate_sql
    sub_list.append(obj[key])
TypeError: string indices must be integers
[2022-06-07 13:55:05,822] {taskinstance.py:1272} INFO - Marking task as FAILED. dag_id=todoist_load_to_pg, task_id=generate_sql, execution_date=20220607T135501, start_date=20220607T135505, end_date=20220607T135505
[2022-06-07 13:55:05,838] {standard_task_runner.py:89} ERROR - Failed to execute job 463 for task generate_sql
Traceback (most recent call last):
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/opt/bitnami/airflow/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/bitnami/airflow/dags/todoist_load_to_pg.py", line 47, in generate_sql
    sub_list.append(obj[key])
TypeError: string indices must be integers
[2022-06-07 13:55:05,862] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-06-07 13:55:05,896] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
